spring:
  datasource:
    url: jdbc:tc:postgresql:15:///testdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  test:
    database:
      replace: none