spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/support
    username: username
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
  application:
    name: api-support
  security:
    jwt:
      secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
      expiration-time: 3600
      refresh-token-expiration: 600000
logging:
  level:
    root: INFO
    com.security.apisupport: DEBUG